language: go

go:
  - 1.x

os:
  - linux

env:
  global:
    - GO111MODULE=on
    - GOFLAGS="-mod=readonly"
    
go_import_path: github.com/Oppodelldog/dockertest

services:
  - docker

script:
  - docker pull golang:1.16.8
  - docker pull busybox:latest
  - make ci